[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ba-gatcha-sim"
authors = [
    { name = "mizma", email = "omoikane@path-works.net"},
]
description = "BlueArchive gatcha monte-carlo simulation"
readme = "README.md"
requires-python = ">=3.11"
#keywords = ["one", "two"]
license = {text = "LICENSE"}
classifiers = [
    # Maturity of the project
    # 3 - Alpha
    # 4 - Beta
    # 5 - Production/Stable
    'Development Status :: 3 - Alpha',
    'Environment :: Console',
    'Intended Audience :: End Users/Desktop',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows :: Windows 10',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.11',
    'Topic :: Utilities',
]
dependencies = [
    'click>=8,<9',
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pyinstaller","build","twine"]

[project.urls]
homepage = "https://github.com/mizma/ba-gatcha-sim/"
documentation = "https://github.com/mizma/ba-gatcha-sim/blob/main/README.md"
repository = "https://github.com/mizma/ba-gatcha-sim.git"
changelog = "https://github.com/mizma/ba-gatcha-sim/blob/main/CHANGELOG.md"

[project.scripts]
basim = "ba_gatcha_sim.cli:main"

[tool.setuptools.packages.find]
exclude = ["build", "test"]

[tool.setuptools.dynamic]
version = {attr = "ba_gatcha_sim.__version__"}

[tool.setuptools_scm]
write_to = "ba_gatcha_sim/_version.py"